# PHPStan Report - Livello 1

## Errori rilevati
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Columns\TextColumn. (line 17)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Columns\TextColumn. (line 20)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Columns\TextColumn. (line 23)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Columns\TextColumn. (line 26)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Columns\BadgeColumn. (line 29)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Columns\TextColumn. (line 36)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Filters\SelectFilter. (line 45)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Filters\SelectFilter. (line 53)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Actions\EditAction. (line 65)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Actions\DeleteAction. (line 66)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Actions\Action. (line 67)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Actions\DeleteBulkAction. (line 77)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Filament/Resources/DatabaseConnectionResource/Pages/ListDatabaseConnections.php: Call to static method make() on an unknown class Modules\Setting\Filament\Resources\DatabaseConnectionResource\Pages\Tables\Actions\CreateAction. (line 84)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$driver. (line 40)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$host. (line 41)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$port. (line 42)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$database. (line 43)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$username. (line 44)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$password. (line 45)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$prefix. (line 48)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$strict. (line 49)
* /var/www/html/_bases/base_quaeris_fila3_mono/laravel/Modules/Setting/app/Models/DatabaseConnection.php: Access to an undefined property Modules\Setting\Models\DatabaseConnection::$engine. (line 50)

## Soluzioni proposte

> TODO: descrivere soluzioni architetturali e funzionali
